config/routes.rb
GraphqlMetrics::Engine.routes.draw do
  root "dashboard#index"
  resources :queries, only: :show do
  end
end

app/controllers/graphql_metrics/application_controller.rb
module GraphqlMetrics
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/graphql_metrics/dashboard_controller.rb
require_dependency "graphql_metrics/application_controller"
require "graphql_metrics/version"

module GraphqlMetrics
  class DashboardController < ApplicationController
    def index
    end
  end
end

app/controllers/graphql_metrics/queries_controller.rb
module GraphqlMetrics
  class QueriesController < ApplicationController
    layout "graphql_metrics/application"

    def index
    end

    def show
      @query = GraphqlMetrics::Store.instance.queries[params[:id].to_i]
    end
  end
end

app/helpers/graphql_metrics/application_helper.rb
module GraphqlMetrics
  module ApplicationHelper
    def ok(query)
      b = x = {}
      for f in query.fields
        x = b
        for k, i in f.path.each_with_index
          x[k] = (i == f.path.length - 1 ? f : {})
          x = x[k]
        end
      end
      b
    end
  end
end

app/views/graphql_metrics/dashboard/index.html.slim
h1 Graphql Metrics #{GraphqlMetrics::VERSION}

.blank Pick a query left

app/views/graphql_metrics/queries/show.html.slim
h1 Query ##{params[:id]} - #{@query.fields.count} fields - #{@query.time.round(2)}ms 

h2 Variables
pre.code=@query.query.provided_variables.to_json

h2 10 slowest fields
= render "graphql_metrics/shared/fields", fields: @query.fields.sort_by {|x|x.time}.reverse.take(10)

/ =JSON.pretty_generate(ok(@query))
h2 Query
pre.code=@query.to_query_string

h2 Result
pre.code=JSON.pretty_generate(@query.query.result["data"])

h2 All fields
= render "graphql_metrics/shared/fields", fields: @query.fields

app/views/graphql_metrics/shared/_fields.html.slim
ul
  - for field in fields
    li
      = field.path.join('.')
      .type #{field.type}.#{field.name}
      = " "
      b #{field.time.round(2)}ms
      - field.annotations.each do |x|
        .annotation=x

app/views/graphql_metrics/shared/_queries.html.slim
h2=link_to "#{GraphqlMetrics::Store.instance.queries.count} queries", root_path
ul
  - a = GraphqlMetrics::Store.instance.queries.count-1
  - GraphqlMetrics::Store.instance.queries.reverse.each_with_index do |query,i|
    = link_to(query_path(a-i)) do
      li class=[(a-i).to_s == params[:id] ? "active" : ""]
        span.no ##{(a-i)} - #{query.time.round(2)}ms - #{query.fields.count} fields
        pre= query.to_query_string
        div
          strong 

app/views/layouts/graphql_metrics/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Graphql Metrics
    = stylesheet_link_tag "graphql_metrics/application", media: "all"
    = csrf_meta_tags
    link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"

  body
    .wrapper
      .left= render "graphql_metrics/shared/queries"
      .right= yield
 